In [2]:
!pip install pdfplumber

Collecting pdfplumber
  Downloading pdfplumber-0.11.4-py3-none-any.whl.metadata (41 kB)
Collecting pdfminer.six==20231228 (from pdfplumber)
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in c:\users\arab soft\anaconda3\lib\site-packages (from pdfplumber) (10.2.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.0-py3-none-win_amd64.whl.metadata (48 kB)
Requirement already satisfied: charset-normalizer>=2.0.0 in c:\users\arab soft\anaconda3\lib\site-packages (from pdfminer.six==20231228->pdfplumber) (2.0.4)
Requirement already satisfied: cryptography>=36.0.0 in c:\users\arab soft\anaconda3\lib\site-packages (from pdfminer.six==20231228->pdfplumber) (42.0.2)
Requirement already satisfied: cffi>=1.12 in c:\users\arab soft\anaconda3\lib\site-packages (from cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (1.16.0)
Requirement already satisfied: pycparser in c:\users\arab soft\anaconda3\lib\site-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (2.21)
Downloading pdfplumber-0.11.4-py3-none-any.whl (59 kB)
Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
   ---------------------------------------- 0.0/5.6 MB ? eta -:--:--
   --------- ------------------------------ 1.3/5.6 MB 8.4 MB/s eta 0:00:01
   ---------------- ----------------------- 2.4/5.6 MB 5.6 MB/s eta 0:00:01
   ------------------------ --------------- 3.4/5.6 MB 6.1 MB/s eta 0:00:01
   ----------------------------------- ---- 5.0/5.6 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 5.6/5.6 MB 5.9 MB/s eta 0:00:00
Downloading pypdfium2-4.30.0-py3-none-win_amd64.whl (2.9 MB)
   ---------------------------------------- 0.0/2.9 MB ? eta -:--:--
   ------------------ --------------------- 1.3/2.9 MB 7.5 MB/s eta 0:00:01
   ------------------------------------ --- 2.6/2.9 MB 6.9 MB/s eta 0:00:01
   ---------------------------------------- 2.9/2.9 MB 6.5 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20231228 pdfplumber-0.11.4 pypdfium2-4.30.0

In [5]:
import pandas as pd
import pdfplumber
from PIL import Image

In [6]:
pdf = pdfplumber.open('declaration.pdf')

In [8]:
p0=pdf.pages[0]
p0

In [26]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[0]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])
for column in ["Taxpayer Identification"]:
    df[column] = df[column].str.replace(" ", "")
# Close the PDF
pdf.close()
df1

                             Taxpayer Identification
0  TIN : 500036301\nName / Company name : ARCELOR...

In [23]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[0]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])
for column in ["Taxpayer Identification"]:
    df[column] = df[column].str.replace(" ", "")
# Close the PDF
pdf.close()
df1

,Group,Line,Amount,Tax Rate %,Taxable Income
0,Calcul,1-NetIncomeorNetLoss(Line35of\nIncomeStatement),2983241.63,0.00,0.00
1,None,2-Addexpensesnotallowableasperthe\nrevenuecode...,0,0.00,0.00
2,None,3-Deducttaxincentiveaspertherevenue\ncode.(Sch...,0,0.00,0.00
3,None,4-AdjustedNetIncome(Line1plusLine2\nminusLine3),2983241.63,0.00,0.00
4,None,5-Addnetprofitorlossfromrentand\nroyalties,0.00,0.00,0.00
5,None,6-Addgainorlossfromdaleofproperty,0.00,0.00,0.00
6,None,"7-Addotherincome(dividends,interest&\nextraord...",0,0.00,0.00
7,None,8-Deductoperatinglosscarriedforward,0.00,0.00,0.00
8,None,9-Deductextraodinaryexpenses,0,0.00,0.00

In [ ]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[0]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])
for column in ["Taxpayer Identification"]:
    df[column] = df[column].str.replace(" ", "")
# Close the PDF
pdf.close()
df1

In [27]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[2]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])
for column in ["Taxpayer Identification"]:
    df[column] = df[column].str.replace(" ", "")
# Close the PDF
pdf.close()
df1

,Group,Line,Amount,Tax Rate %,Taxable Income
0,Calcul,"10- Total Taxable Income (Add Lines 4,5,6,7\na...",2983241.63,0.00,0.00
1,None,11- Income Tax for Rate 30 %,0,30 %,0.00
2,None,12- Income Tax for Rate 25 %,0,25 %,0.00
3,None,13- Income Tax for Rate,745810.4075,25,2983241.63
4,None,14- Income Tax,0,0.00,0.00
5,None,15- Total Income Tax ( Add line 11-14),745810.41,0.00,0.00
6,None,16- Minimum Tax (2% of Income Statement\nLine ...,0,0.00,0.00
7,None,"17- Tax To Pay (Line 15 or Line\n16,whichever ...",745810.41,0.00,0.00
8,None,18- Tax Credit Claimed,0.00,0.00,0.00
9,None,19- Advance payments (from Schedule 1),0,0.00,0.00
10,None,20- Minimum tax credit from previous\nyear(s) ...,0,0.00,0.00
11,None,21- Other Creditable Withholdings\n(withholdin...,0,0.00,0.00
12,None,22- Overpayement for previous years,0.00,0.00,0.00
13,None,23- Payment Due or Overpayment (Deduct\nLine 1...,745810.41,0.00,0.00

In [32]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[3]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

In [35]:
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

                           Group  \
0   Income\nFinancial\nStatement
1                           None
2                           None
3                           None
4                           None
5                           None
6                           None
7                           None
8                           None
9                           None
10                          None

                                                Line Amount at End of\nYear
0                            1- Gross Sales/Receipts             2997853.63
1                                   2- Sales Returns                      0
2          3- Net Sales/Net Receipts(Line 1- line 2)             2997853.63
3                              4- Cost of Goods Sold                      0
4         5- Gross Profit (Loss)(Line 3 minus Line4)             2997853.63
5   6- Selling, General and Administrative\nExpenses                      0
6              7- Advertisement and Public Relations                      0
7                 8- Bad debt from sales or services                      0
8                                    9- Bank Charges                      0
9    10- Car and truck expenses (fuel and\nLubricant                      0
10                                   11- Commissions                      0

,Group,Line,Amount at End of\nYear
0,Income\nFinancial\nStatement,1- Gross Sales/Receipts,2997853.63
1,None,2- Sales Returns,0
2,None,3- Net Sales/Net Receipts(Line 1- line 2),2997853.63
3,None,4- Cost of Goods Sold,0
4,None,5- Gross Profit (Loss)(Line 3 minus Line4),2997853.63
5,None,"6- Selling, General and Administrative\nExpenses",0
6,None,7- Advertisement and Public Relations,0
7,None,8- Bad debt from sales or services,0
8,None,9- Bank Charges,0
9,None,10- Car and truck expenses (fuel and\nLubricant,0
10,None,11- Commissions,0

In [36]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[4]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

                           Group  \
0   Income\nFinancial\nStatement
1                           None
2                           None
3                           None
4                           None
5                           None
6                           None
7                           None
8                           None
9                           None
10                          None
11                          None
12                          None
13                          None

                                                 Line Amount at End of\nYear
0                     12- Dues, fees and publications                      0
1                       13- Employee benefit programs                      0
2                        14- Charitable contributions                      0
3            15- Exploration and development expenses                      0
4                    16- Freight not included in COGS                      0
5                               17- Insurance expense                      0
6                     18- Legal and professional fees                  14612
7   19- Management Fees (Restricted to 2% of\nothe...                      0
8                                 20- Office supplies                      0
9                                         21- Postage                      0
10                                   22- Rent expense                      0
11       23- Reclamation and decommissioning\nexpense                      0
12                        24- Repairs and maintenance                      0
13        25- Royalty and surtax for mining companies                      0

,Group,Line,Amount at End of\nYear
0,Income\nFinancial\nStatement,"12- Dues, fees and publications",0
1,None,13- Employee benefit programs,0
2,None,14- Charitable contributions,0
3,None,15- Exploration and development expenses,0
4,None,16- Freight not included in COGS,0
5,None,17- Insurance expense,0
6,None,18- Legal and professional fees,14612
7,None,19- Management Fees (Restricted to 2% of\nothe...,0
8,None,20- Office supplies,0
9,None,21- Postage,0
10,None,22- Rent expense,0
11,None,23- Reclamation and decommissioning\nexpense,0
12,None,24- Repairs and maintenance,0
13,None,25- Royalty and surtax for mining companies,0

In [37]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[5] #page6

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

                           Group  \
0   Income\nFinancial\nStatement
1                           None
2                           None
3                           None
4                           None
5                           None
6                           None
7                           None
8                           None
9                           None
10                          None
11                          None
12                          None
13                          None

                                                 Line Amount at End of\nYear
0                         26- Utilities and telephone                      0
1                        27- Travel and entertainment                      0
2   28- Salaries, wages and other allowances (not\...                      0
3                                  29- Other expenses                      0
4   30- Total selling, General and Administrative\...                  14612
5   31- Operating income before depreciation\n(lin...             2983241.63
6   32- Depreciation, depletionand amortization\nn...                      0
7   33- Net income after depreciation (Line 31 -\n...             2983241.63
8                   34- Interest ant related expenses                      0
9   35- Net income after interest (Line 33 - Line\...             2983241.63
10                            36- Add Interest income                      0
11                            37- Add Dividend income                      0
12                       38- Add Extraordinary income                      0
13                   39- Deduct Extraordinary expense                      0

,Group,Line,Amount at End of\nYear
0,Income\nFinancial\nStatement,26- Utilities and telephone,0
1,None,27- Travel and entertainment,0
2,None,"28- Salaries, wages and other allowances (not\...",0
3,None,29- Other expenses,0
4,None,"30- Total selling, General and Administrative\...",14612
5,None,31- Operating income before depreciation\n(lin...,2983241.63
6,None,"32- Depreciation, depletionand amortization\nn...",0
7,None,33- Net income after depreciation (Line 31 -\n...,2983241.63
8,None,34- Interest ant related expenses,0
9,None,35- Net income after interest (Line 33 - Line\...,2983241.63
10,None,36- Add Interest income,0
11,None,37- Add Dividend income,0
12,None,38- Add Extraordinary income,0
13,None,39- Deduct Extraordinary expense,0

In [42]:
import pdfplumber
import pandas as pd
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page (page 7 in this case)
p0 = pdf.pages[6]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

# Extract tables (using extract_tables to get multiple tables)
tables = p0.extract_tables()

# Check if there are multiple tables
if len(tables) >= 2:
    # First table
    table_1 = tables[0]
    df1 = pd.DataFrame(table_1[1:], columns=table_1[0])

    # Second table (assuming the second one has different columns)
    table_2 = tables[1]
    df2 = pd.DataFrame(table_2[1:], columns=["Group", "Line", "Amount at Beginning of Year", "Amount at End of Year"])

    # Optional: clean up the "Group" column in df2
    if "Group" in df2.columns:
        df2["Group"] = df2["Group"].str.replace(" ", "")
    else:
        print("'Group' column not found in the second table")

    # Close the PDF
    pdf.close()

    # Display the results
    print("First Table:")
    print(df1)
    print("\nSecond Table:")
    print(df2)
else:
    print("Unable to find two tables on the page.")

# Close the PDF (in case not done earlier)
pdf.close()

First Table:
                          Group  \
0  Income\nFinancial\nStatement
1                          None
2                          None
3                          None
4                          None
5                          None

                                                Line Amount at End of\nYear
0  40- Net income before tax (Line 35 add line\n3...             2983241.63
1                                     41- Income Tax            745810.4075
2  42- Net income after tax (Line 35 minus line\n41)           2237431.2225
3               43- Deduct Dividends preferred stock                      0
4            44- Deduct Dividends non-prefreed stock                      0
5  45- Net income or loss transfeered to retained...           2237431.2225

Second Table:
          Group                             Line Amount at Beginning of Year  \
0  BalanceSheet  1- Cash in hand and at the bank                     3567964
1          None            2- Account receivable                     4089553

  Amount at End of Year
0               4427705
1               5155662

In [44]:
df1

,Group,Line,Amount at End of\nYear
0,Income\nFinancial\nStatement,40- Net income before tax (Line 35 add line\n3...,2983241.63
1,None,41- Income Tax,745810.4075
2,None,42- Net income after tax (Line 35 minus line\n41),2237431.2225
3,None,43- Deduct Dividends preferred stock,0
4,None,44- Deduct Dividends non-prefreed stock,0
5,None,45- Net income or loss transfeered to retained...,2237431.2225

In [45]:
df2

,Group,Line,Amount at Beginning of Year,Amount at End of Year
0,BalanceSheet,1- Cash in hand and at the bank,3567964,4427705
1,None,2- Account receivable,4089553,5155662

In [46]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[7] #page6

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

           Group                                               Line  \
0   BalanceSheet                    3- Less Allowance for bad debts
1           None                                       4- Inventory
2           None                                5- Prepaid expenses
3           None                          6- Short-term investments
4           None                               7- Prepaid insurance
5           None                            8- Other current assets
6           None  9- Total Current Assets (Add Lines 1,2,4-8\nmi...
7           None                                       10- Building
8           None                                           11- Land
9           None                            12- Plant and Machinery
10          None                                  13- Capital lease
11          None                             14- Leasehold premises
12          None                                 15- Motor vehicles
13          None      16- Less Accummulated\ndepreciation/depletion

   Amount at Beginning\nof year Amount at End of\nYear
0                          0.00                   0.00
1                          0.00                   0.00
2                          0.00                   0.00
3                          0.00                   0.00
4                          0.00                   0.00
5                          0.00                   0.00
6                       7657517                9583367
7                          0.00                   0.00
8                          0.00                   0.00
9                          0.00                   0.00
10                         0.00                   0.00
11                         0.00                   0.00
12                         0.00                   0.00
13                         0.00                   0.00

,Group,Line,Amount at Beginning\nof year,Amount at End of\nYear
0,BalanceSheet,3- Less Allowance for bad debts,0.00,0.00
1,None,4- Inventory,0.00,0.00
2,None,5- Prepaid expenses,0.00,0.00
3,None,6- Short-term investments,0.00,0.00
4,None,7- Prepaid insurance,0.00,0.00
5,None,8- Other current assets,0.00,0.00
6,None,"9- Total Current Assets (Add Lines 1,2,4-8\nmi...",7657517,9583367
7,None,10- Building,0.00,0.00
8,None,11- Land,0.00,0.00
9,None,12- Plant and Machinery,0.00,0.00
10,None,13- Capital lease,0.00,0.00
11,None,14- Leasehold premises,0.00,0.00
12,None,15- Motor vehicles,0.00,0.00
13,None,16- Less Accummulated\ndepreciation/depletion,0.00,0.00

In [47]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[8] #page6

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

           Group                                               Line  \
0   BalanceSheet  17- Net Tangible Assets (add Lines 10-15\nminu...
1           None                                        18- Patents
2           None                                       19- Goodwill
3           None                                     20- Franchises
4           None                                     21- Trademarks
5           None                                      22- Copyright
6           None                       23- Other non-current assets
7           None                  24- Less Accumulated amortization
8           None  25- Net Intangible Assets (Add Lines 18-23\nmi...
9           None         26- TOTAL ASSETS (Add Lines 9,17, and\n25)
10          None                            27- Current liabilities
11          None                                   28- Note Payable
12          None                               29- Accounts payable
13          None                             30- Income tax payable

   Amount at Beginning\nof year Amount at End of\nYear
0                             0                      0
1                          0.00                   0.00
2                          0.00                   0.00
3                          0.00                   0.00
4                          0.00                   0.00
5                          0.00                   0.00
6                          0.00                   0.00
7                          0.00                   0.00
8                             0                      0
9                       7657517                9583367
10                         0.00                   0.00
11                         0.00                   0.00
12                         0.00                   0.00
13                   1011019.44              719675.61

,Group,Line,Amount at Beginning\nof year,Amount at End of\nYear
0,BalanceSheet,17- Net Tangible Assets (add Lines 10-15\nminu...,0,0
1,None,18- Patents,0.00,0.00
2,None,19- Goodwill,0.00,0.00
3,None,20- Franchises,0.00,0.00
4,None,21- Trademarks,0.00,0.00
5,None,22- Copyright,0.00,0.00
6,None,23- Other non-current assets,0.00,0.00
7,None,24- Less Accumulated amortization,0.00,0.00
8,None,25- Net Intangible Assets (Add Lines 18-23\nmi...,0,0
9,None,"26- TOTAL ASSETS (Add Lines 9,17, and\n25)",7657517,9583367
10,None,27- Current liabilities,0.00,0.00
11,None,28- Note Payable,0.00,0.00
12,None,29- Accounts payable,0.00,0.00
13,None,30- Income tax payable,1011019.44,719675.61

In [48]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[9] #page6

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

           Group                                               Line  \
0   BalanceSheet  31- Mortgages, notes and bonds payable less\nt...
1           None                                32- Bank overdrafts
2           None  33- Mortgages, notes and bonds payable in 1\ny...
3           None                      34- Other current liabilities
4           None     35- Total Current Liabilities (add lines 27-34
5           None                    37- Other long-term liabilities
6           None                        36- Long-term business loan
7           None    38- Total Liabilities (add lines 35, 36 and 37)
8           None                              39- Retained earnings
9           None                                        40- Capital
10          None    41- Shareholder's equity (add lines 39 and\n40)
11          None  42- TOTAL LIABILITIES AND\nSHAREHOLDER'S EQUIT...

   Amount at Beginning\nof year Amount at End of\nYear
0                          0.00                   0.00
1                          0.00                   0.00
2                          0.00                   0.00
3                      24115.79               14611.93
4                    1035135.23              734287.54
5                          0.00                   0.00
6                          0.00                   0.00
7                    1035135.23              734287.54
8                    6622281.77             8848979.46
9                           100                    100
10                   6622381.77             8849079.46
11                      7657517                9583367

,Group,Line,Amount at Beginning\nof year,Amount at End of\nYear
0,BalanceSheet,"31- Mortgages, notes and bonds payable less\nt...",0.00,0.00
1,None,32- Bank overdrafts,0.00,0.00
2,None,"33- Mortgages, notes and bonds payable in 1\ny...",0.00,0.00
3,None,34- Other current liabilities,24115.79,14611.93
4,None,35- Total Current Liabilities (add lines 27-34,1035135.23,734287.54
5,None,37- Other long-term liabilities,0.00,0.00
6,None,36- Long-term business loan,0.00,0.00
7,None,"38- Total Liabilities (add lines 35, 36 and 37)",1035135.23,734287.54
8,None,39- Retained earnings,6622281.77,8848979.46
9,None,40- Capital,100,100
10,None,41- Shareholder's equity (add lines 39 and\n40),6622381.77,8849079.46
11,None,42- TOTAL LIABILITIES AND\nSHAREHOLDER'S EQUIT...,7657517,9583367

In [50]:
import pdfplumber
import pandas as pd
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page (page 7 in this case)
p0 = pdf.pages[10]

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

# Extract tables (using extract_tables to get multiple tables)
tables = p0.extract_tables()

# Check if there are multiple tables
if len(tables) >= 2:
    # First table
    table_1 = tables[0]
    df1 = pd.DataFrame(table_1[1:], columns=table_1[0])

    # Second table (assuming the second one has different columns)
    table_2 = tables[1]
    df2 = pd.DataFrame(table_2[1:], columns=["Group", "Line", "Addition", "Asset Group", "Beginning Year Accum Depreciation", "Beginning Year Acquisition Cost",
                                            "Beginning Year Book Value"])

    # Optional: clean up the "Group" column in df2
    if "Group" in df2.columns:
        df2["Group"] = df2["Group"].str.replace(" ", "")
    else:
        print("'Group' column not found in the second table")

    # Close the PDF
    pdf.close()

    # Display the results
    print("First Table:")
    print(df1)
    print("\nSecond Table:")
    print(df2)
else:
    print("Unable to find two tables on the page.")

# Close the PDF (in case not done earlier)
pdf.close()

First Table:
                                     Group                Line Additions  \
0  Schedule 3\nDepreciation\n(fixed assets                   .      0.00
1                                     None                   .      0.00
2                                     None                   .      0.00
3                                     None                   .      0.00
4                                     None                   .      0.00
5                                     None  Total Depreciation      0.00

                  Asset Group Beginning Year Accum\nDepreciation  \
0  Tangible Movable\nProperty                               0.00
1             Heavy Machinery                               0.00
2             Light Machinery                               0.00
3     Tangible Fixed Property                               0.00
4                   Buildings                               0.00
5                        0.00                               0.00

  Beginning Year\nAcquisition Cost Beginning Year Book\nValue
0                             0.00                       0.00
1                             0.00                       0.00
2                             0.00                       0.00
3                             0.00                       0.00
4                             0.00                       0.00
5                             0.00                       0.00

Second Table:
                                   Group Line Addition Asset Group  \
0  Schedule3\nDepreciation\n(fixedassets    .     0.00        0.00
1                                   None    .     0.00        Pool
2                                   None    .     0.00        Pool

  Beginning Year Accum Depreciation Beginning Year Acquisition Cost  \
0                              0.00                            0.00
1                              0.00                            0.00
2                              0.00                            0.00

  Beginning Year Book Value
0                      0.00
1                      0.00
2                      0.00

In [51]:
df1

,Group,Line,Additions,Asset Group,Beginning Year Accum\nDepreciation,Beginning Year\nAcquisition Cost,Beginning Year Book\nValue
0,Schedule 3\nDepreciation\n(fixed assets,.,0.00,Tangible Movable\nProperty,0.00,0.00,0.00
1,None,.,0.00,Heavy Machinery,0.00,0.00,0.00
2,None,.,0.00,Light Machinery,0.00,0.00,0.00
3,None,.,0.00,Tangible Fixed Property,0.00,0.00,0.00
4,None,.,0.00,Buildings,0.00,0.00,0.00
5,None,Total Depreciation,0.00,0.00,0.00,0.00,0.00

In [52]:
df2

,Group,Line,Addition,Asset Group,Beginning Year Accum Depreciation,Beginning Year Acquisition Cost,Beginning Year Book Value
0,Schedule3\nDepreciation\n(fixedassets,.,0.00,0.00,0.00,0.00,0.00
1,None,.,0.00,Pool,0.00,0.00,0.00
2,None,.,0.00,Pool,0.00,0.00,0.00

In [53]:
import pdfplumber
import pandas as pd
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the specific page (page 10 in this case)
p0 = pdf.pages[11]

# Convert the PDF page to an image (optional, for visualization)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL (optional)
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

# Extract tables from the page
tables = p0.extract_tables()

# Check if there are at least two tables on the page
if len(tables) >= 2:
    # First table
    table_1 = tables[0]
    df1 = pd.DataFrame(table_1[1:], columns=table_1[0])  # Automatically use extracted columns
    
    # Second table
    table_2 = tables[1]
    df2 = pd.DataFrame(table_2[1:], columns=table_2[0])  # Automatically use extracted columns

    # Ensure both tables have "Group" and "Line" columns, if present
    for df, table_num in zip([df1, df2], ["First", "Second"]):
        if "Group" in df.columns and "Line" in df.columns:
            df["Group"] = df["Group"].str.replace(" ", "")  # Clean up the "Group" column
        else:
            print(f"'Group' and 'Line' columns not found in the {table_num} table")

    # Close the PDF
    pdf.close()

    # Display the results
    print("First Table:")
    print(df1)
    print("\nSecond Table:")
    print(df2)
else:
    print("Unable to find two tables on the page.")

# Close the PDF (in case not done earlier)
pdf.close()

First Table:
                                   Group                Line Depreciation  \
0  Schedule3\nDepreciation\n(fixedassets                   .         0.00
1                                   None                   .         0.00
2                                   None  Total Depreciation            0

  Depreciation Method Disposals Ending Year Accum\nDepreciation  \
0                0.00      0.00                            0.00
1       STRAIGHT LINE      0.00                            0.00
2                0.00      0.00                            0.00

  Ending Year\nAcquisition Cost
0                          0.00
1                          0.00
2                          0.00

Second Table:
                                   Group                Line  \
0  Schedule3\nDepreciation\n(fixedassets                   .
1                                   None                   .
2                                   None                   .
3                                   None                   .
4                                   None                   .
5                                   None  Total Depreciation

  Ending Year Book\nValue Incentive Cost
0                    0.00           0.00
1                    0.00           0.00
2                    0.00           0.00
3                    0.00           0.00
4                    0.00           0.00
5                    0.00           0.00

In [54]:
df1

,Group,Line,Depreciation,Depreciation Method,Disposals,Ending Year Accum\nDepreciation,Ending Year\nAcquisition Cost
0,Schedule3\nDepreciation\n(fixedassets,.,0.00,0.00,0.00,0.00,0.00
1,None,.,0.00,STRAIGHT LINE,0.00,0.00,0.00
2,None,Total Depreciation,0,0.00,0.00,0.00,0.00

In [55]:
df2

,Group,Line,Ending Year Book\nValue,Incentive Cost
0,Schedule3\nDepreciation\n(fixedassets,.,0.00,0.00
1,None,.,0.00,0.00
2,None,.,0.00,0.00
3,None,.,0.00,0.00
4,None,.,0.00,0.00
5,None,Total Depreciation,0.00,0.00

In [56]:
import pdfplumber
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the first page
p0 = pdf.pages[12] #page6

# Convert the PDF page to an image (optional, if rendering is supported)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()
table = p0.extract_table()
df1 = pd.DataFrame(table[1:], columns=table[0])

# Ensure the "Group" column exists
if "Group" in df1.columns:
    df1["Group"] = df1["Group"].str.replace(" ", "")
else:
    print("'Group' column not found in the DataFrame")

# Close the PDF
pdf.close()

# Display the result
print(df1)
df1

                                               Group  \
0  Schedule5\nNon-\nallowable\nexpensesas\nperrev...
1                                               None
2                                               None
3                                               None
4                                               None
5                                               None
6                                               None
7                                               None

                                                Line Amount
0  1- Deduction in excess special investment\ninc...   0.00
1  2- Charitable expenses which are not\nconsiste...   0.00
2  3- Excessive deprecation not consistent with\n...   0.00
3  4- Excessive interest expense (thin\ncapitaliz...   0.00
4  5- Excessive de-commissioning expenses\n(secti...   0.00
5  6- Management fees above 2 of other\noperation...   0.00
6  7- Bad debts written off in excess of what is\...   0.00
7  8- Any expenses not related to the business\ns...   0.00

,Group,Line,Amount
0,Schedule5\nNon-\nallowable\nexpensesas\nperrev...,1- Deduction in excess special investment\ninc...,0.00
1,None,2- Charitable expenses which are not\nconsiste...,0.00
2,None,3- Excessive deprecation not consistent with\n...,0.00
3,None,4- Excessive interest expense (thin\ncapitaliz...,0.00
4,None,5- Excessive de-commissioning expenses\n(secti...,0.00
5,None,6- Management fees above 2 of other\noperation...,0.00
6,None,7- Bad debts written off in excess of what is\...,0.00
7,None,8- Any expenses not related to the business\ns...,0.00

In [57]:
import pdfplumber
import pandas as pd
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the specific page (page 10 in this case)
p0 = pdf.pages[13]

# Convert the PDF page to an image (optional, for visualization)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL (optional)
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

# Extract tables from the page
tables = p0.extract_tables()

# Check if there are at least two tables on the page
if len(tables) >= 2:
    # First table
    table_1 = tables[0]
    df1 = pd.DataFrame(table_1[1:], columns=table_1[0])  # Automatically use extracted columns
    
    # Second table
    table_2 = tables[1]
    df2 = pd.DataFrame(table_2[1:], columns=table_2[0])  # Automatically use extracted columns

    # Ensure both tables have "Group" and "Line" columns, if present
    for df, table_num in zip([df1, df2], ["First", "Second"]):
        if "Group" in df.columns and "Line" in df.columns:
            df["Group"] = df["Group"].str.replace(" ", "")  # Clean up the "Group" column
        else:
            print(f"'Group' and 'Line' columns not found in the {table_num} table")

    # Close the PDF
    pdf.close()

    # Display the results
    print("First Table:")
    print(df1)
    print("\nSecond Table:")
    print(df2)
else:
    print("Unable to find two tables on the page.")

# Close the PDF (in case not done earlier)
pdf.close()

First Table:
                                               Group  \
0  Schedule5\nNon-\nallowable\nexpensesas\nperrev...
1                                               None
2                                               None

                                                Line Amount
0  9- Expenses not allowable as per section 705\n...   0.00
1  10- Other non-allowable expenses as per the\nr...   0.00
2                             Total (Add Lines 1-10)   0.00

Second Table:
                        Group  \
0  Schedule6\nTax\nIncentives
1                        None

                                                Line Amount
0  1- Accelerated depreciation and amortization\n...   0.00
1  2- Expenses as per special investment\nincenti...   0.00

In [58]:
df1

,Group,Line,Amount
0,Schedule5\nNon-\nallowable\nexpensesas\nperrev...,9- Expenses not allowable as per section 705\n...,0.00
1,None,10- Other non-allowable expenses as per the\nr...,0.00
2,None,Total (Add Lines 1-10),0.00

In [59]:
df2

,Group,Line,Amount
0,Schedule6\nTax\nIncentives,1- Accelerated depreciation and amortization\n...,0.00
1,None,2- Expenses as per special investment\nincenti...,0.00

In [65]:
import pdfplumber
import pandas as pd
from PIL import Image

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the specific page (page 10 in this case)
p0 = pdf.pages[14]

# Convert the PDF page to an image (optional, for visualization)
p0_image = p0.to_image()

# Save the page as an image (optional)
p0_image.save("p0_image.png")

# Open the saved image with PIL (optional)
img = Image.open("p0_image.png")

# Display the image (if in an interactive environment)
img.show()

# Extract tables from the page
tables = p0.extract_tables()

# Check if there are at least two tables on the page
if len(tables) >= 2:
    # First table (structure with 7 columns)
    table_1 = tables[0]
    df1 = pd.DataFrame(table_1[1:], columns=table_1[0])  # Automatically use extracted columns
    
    # Second table (which includes "Full Name" and "Nationality")
    table_2 = tables[1]
    df2 = pd.DataFrame(table_2[1:], columns=table_2[0])  # Automatically use extracted columns

    # Ensure both tables are processed accordingly

    # For the first table: check if "Group" and "Line" columns exist
    if "Group" in df1.columns and "Line" in df1.columns:
        df1["Group"] = df1["Group"].str.replace(" ", "")  # Clean up the "Group" column
    else:
        print("'Group' and 'Line' columns not found in the First table")

    # For the second table: handle "Full Name" and "Nationality"
    if "Full Name" in df2.columns and "Nationality" in df2.columns:
        # Clean up if necessary
        df2["Full Name"] = df2["Full Name"].str.strip()  # Clean up spaces from "Full Name"
        df2["Nationality"] = df2["Nationality"].str.strip()  # Clean up spaces from "Nationality"
    else:
        print("'Full Name' and 'Nationality' columns not found in the Second table")

    # Close the PDF
    pdf.close()

    # Display the results
    print("First Table:")
    print(df1)
    print("\nSecond Table:")
    print(df2)
else:
    print("Unable to find two tables on the page.")

# Close the PDF (in case not done earlier)
pdf.close()

'Full Name' and 'Nationality' columns not found in the Second table
First Table:
                        Group  \
0  Schedule6\nTax\nIncentives
1                        None
2                        None

                                                Line Amount
0  3- Tax incentive on loss carried forward as\np...   0.00
1  4- Tax incentives through other legal\ninsturm...   0.00
2                              Total (Add Lines 1-4)   0.00

Second Table:
                          Full Name Nationalit\ny Date of\nbirth  \
0  ArcelorMittal\nLiberia\nHoldings       Liberia     01/01/2006

  Principal\nResidential\nAddress Date\nbecame\nbeneficial\nowner  \
0  Buchanan,\nGrand Bassa\nCounty                      01/01/2006

  Grounds\non which\nperson in\nbeneficial
0                              Shareholder

In [66]:
df1

,Group,Line,Amount
0,Schedule6\nTax\nIncentives,3- Tax incentive on loss carried forward as\np...,0.00
1,None,4- Tax incentives through other legal\ninsturm...,0.00
2,None,Total (Add Lines 1-4),0.00

,Full Name,Nationalit\ny,Date of\nbirth,Principal\nResidential\nAddress,Date\nbecame\nbeneficial\nowner,Grounds\non which\nperson in\nbeneficial
0,ArcelorMittal\nLiberia\nHoldings,Liberia,01/01/2006,"Buchanan,\nGrand Bassa\nCounty",01/01/2006,Shareholder

In [70]:
import pdfplumber

# Open the PDF
pdf = pdfplumber.open('declaration.pdf')

# Extract the last page (adjust the page index if necessary)
last_page = pdf.pages[-1]

# Extract text from the last page
page_text = last_page.extract_text()

# Check if the relevant text is present
if page_text:
    # Find the specific line containing the amount
    for line in page_text.split("\n"):
        if "Amount on hand to pay" in line:
            # Print the line containing the amount
            print("Extracted Information:")
            print(line)
else:
    print("No text found on the last page.")

# Close the PDF
pdf.close()

Extracted Information:
Amount on hand to pay : $745,810.41 USD