<div style="background-color: #f9f9f9; padding: 20px; border-radius: 10px;">

# <span style="color: #2E86C1;">PDF Table Extraction Notebook</span>

## Overview

This notebook provides a comprehensive approach to extracting tabular data from PDF documents using the <span style="color: #C0392B;">`pdfplumber`</span> library. It enables users to extract multiple tables from specified pages and process them into Pandas DataFrames for further analysis.

<img src="path_to_image/extraction_diagram.png" alt="PDF Extraction" style="width: 100%; border-radius: 10px;" /> <!-- Replace with the actual image path -->

</div>

<div style="background-color: #e9f7ef; padding: 15px; border-radius: 10px;">

## Features

- **PDF File Handling**: Opens and manages PDF files seamlessly.
- **Table Extraction**: Extracts tables from specified pages, handling single or multiple tables.
- **Data Cleaning**: Cleans up specific columns (e.g., removing spaces from the "Group" column).
- **DataFrame Management**: Stores extracted tables as Pandas DataFrames for easy manipulation and analysis.
- **Image Rendering**: Converts pages to images for visual verification of the extracted tables.

</div>

<div style="background-color: #f9f9f9; padding: 15px; border-radius: 10px;">

## Usage

1. **File Path**: Specify the path of the PDF file you wish to analyze.
2. **Page Number**: Set the page number from which you want to extract tables.
3. **Execute the Notebook**: Run the cells to extract tables and view the DataFrames.

</div>

<div style="background-color: #e9f7ef; padding: 15px; border-radius: 10px;">

## Requirements

- Python 3.x
- Pandas
- pdfplumber
- PIL (Pillow)

</div>

<div style="background-color: #f9f9f9; padding: 15px; border-radius: 10px;">

## Example

This notebook is structured to demonstrate the extraction of tables from a sample PDF document, showcasing the results in a clear and organized manner.

<img src="path_to_image/example_output.png" alt="Example Output" style="width: 100%; border-radius: 10px;" /> <!-- Replace with the actual image path -->

</div>

<div style="background-color: #e9f7ef; padding: 15px; border-radius: 10px;">

## Note

Ensure that the specified page contains the expected table structures for optimal extraction.

---

*For any questions or further assistance, please refer to the docu also you could suggest your problems on our discussionmentation of the libraries used or consult the community forums.*

</div>
s used or consult the community forums.*

In [18]:
import pandas as pd
import pdfplumber
from PIL import Image

def open_pdf(file_path):
    """Open a PDF file and return the pdf object."""
    try:
        pdf = pdfplumber.open(file_path)
        return pdf
    except Exception as e:
        print(f"Error opening PDF: {e}")
        return None

def extract_tables_from_page(pdf, page_num):
    """Extract tables from a specified page."""
    try:
        page = pdf.pages[page_num]
        tables = page.extract_tables()
        return tables
    except IndexError:
        print(f"Page {page_num} not found.")
        return []
    except Exception as e:
        print(f"Error extracting tables: {e}")
        return []

def process_tables(tables):
    """Process extracted tables into DataFrames."""
    dfs = []
    for i, table in enumerate(tables):
        df = pd.DataFrame(table[1:], columns=table[0])
        # Optional cleaning of "Group" column
        if "Group" in df.columns:
            df["Group"] = df["Group"].str.replace(" ", "")
        dfs.append(df)
    return dfs

def display_image_from_page(page, save_path="page_image.png"):
    """Convert a page to an image and display it."""
    page_image = page.to_image()
    page_image.save(save_path)
    img = Image.open(save_path)
    img.show()

## Testing the Output

This section describes how the notebook handles the output of extracted tables based on the number of tables present in the specified PDF page.

### Handling Single and Multiple Tables

The extraction process can result in one or more tables being found on the page. To effectively manage the output, the code implements the following logic:

- **Single Table Case**: 
  - If the PDF page contains only one table, the DataFrame representing that table can be accessed directly using `dataframes[0]`. 
  - This means that the output will display only the first (and only) DataFrame without any need for iteration.

- **Multiple Tables Case**: 
  - If the PDF page contains multiple tables, the DataFrames can be accessed using an index ranging from `dataframes[0]` to `dataframes[n-1]`, where `n` is the total number of tables extracted.
  - The code iterates through the `dataframes` list, printing each DataFrame sequentially, which ensures all extracted tables are displayed clearly.

### Example Output Logic

Here's a simplified representation of the output logic:

```python
if dataframes:
    # If there's at least one DataFrame
    for i, df in enumerate(dataframes):
        print(f"Table {i + 1}:")  # Print the table number (1-indexed)
        print(df)                 # Display the DataFrame
else:
    print("No tables found on the specified page.")

## Example 1
This section describes how the notebook handles the output of extracted tables for the third page on declaration document which contain only one table

In [19]:
# Example usage
pdf_file = 'declaration.pdf'
pdf = open_pdf(pdf_file)

if pdf:
    page_num = 2  # Example page number
    tables = extract_tables_from_page(pdf, page_num)
    
    if tables:
        dataframes = process_tables(tables)
        for i, df in enumerate(dataframes):
            print(f"\nTable {i + 1}:")
            print(df)
    else:
        print("No tables found on the specified page.")

    # Close the PDF
    pdf.close()

Table 1:
     Group                                               Line       Amount  \
0   Calcul  10- Total Taxable Income (Add Lines 4,5,6,7\na...   2983241.63
1     None                       11- Income Tax for Rate 30 %            0
2     None                       12- Income Tax for Rate 25 %            0
3     None                            13- Income Tax for Rate  745810.4075
4     None                                     14- Income Tax            0
5     None             15- Total Income Tax ( Add line 11-14)    745810.41
6     None  16- Minimum Tax (2% of Income Statement\nLine ...            0
7     None  17- Tax To Pay (Line 15 or Line\n16,whichever ...    745810.41
8     None                             18- Tax Credit Claimed         0.00
9     None             19- Advance payments (from Schedule 1)            0
10    None  20- Minimum tax credit from previous\nyear(s) ...            0
11    None  21- Other Creditable Withholdings\n(withholdin...            0
12    None                22- Overpayement for previous years         0.00
13    None  23- Payment Due or Overpayment (Deduct\nLine 1...    745810.41

   Tax Rate % Taxable Income
0        0.00           0.00
1        30 %           0.00
2        25 %           0.00
3          25     2983241.63
4        0.00           0.00
5        0.00           0.00
6        0.00           0.00
7        0.00           0.00
8        0.00           0.00
9        0.00           0.00
10       0.00           0.00
11       0.00           0.00
12       0.00           0.00
13       0.00           0.00

In [36]:
dataframes[0]

,Group,Line,Additions,Asset Group,Beginning Year Accum\nDepreciation,Beginning Year\nAcquisition Cost,Beginning Year Book\nValue
0,Schedule3\nDepreciation\n(fixedassets,.,0.00,Tangible Movable\nProperty,0.00,0.00,0.00
1,None,.,0.00,Heavy Machinery,0.00,0.00,0.00
2,None,.,0.00,Light Machinery,0.00,0.00,0.00
3,None,.,0.00,Tangible Fixed Property,0.00,0.00,0.00
4,None,.,0.00,Buildings,0.00,0.00,0.00
5,None,Total Depreciation,0.00,0.00,0.00,0.00,0.00

In [37]:
# Assuming 'dataframes' is a list of DataFrames obtained from the extraction process
if dataframes:
    for i, df in enumerate(dataframes):
        print(f"Table {i + 1}:")  # Using i + 1 to display the table number starting from 1
        print(df)
else:
    print("No tables found on the specified page.")

Table 1:
                                   Group                Line Additions  \
0  Schedule3\nDepreciation\n(fixedassets                   .      0.00
1                                   None                   .      0.00
2                                   None                   .      0.00
3                                   None                   .      0.00
4                                   None                   .      0.00
5                                   None  Total Depreciation      0.00

                  Asset Group Beginning Year Accum\nDepreciation  \
0  Tangible Movable\nProperty                               0.00
1             Heavy Machinery                               0.00
2             Light Machinery                               0.00
3     Tangible Fixed Property                               0.00
4                   Buildings                               0.00
5                        0.00                               0.00

  Beginning Year\nAcquisition Cost Beginning Year Book\nValue
0                             0.00                       0.00
1                             0.00                       0.00
2                             0.00                       0.00
3                             0.00                       0.00
4                             0.00                       0.00
5                             0.00                       0.00
Table 2:
                                   Group Line Depreciation  \
0  Schedule3\nDepreciation\n(fixedassets    .         0.00
1                                   None    .         0.00
2                                   None    .         0.00

  Depreciation Method Disposals Ending Year Accum\nDepreciation  \
0                0.00      0.00                            0.00
1                Pool      0.00                            0.00
2                Pool      0.00                            0.00

  Ending Year\nAcquisition Cost
0                          0.00
1                          0.00
2                          0.00

## Example 2
This section describes how the notebook handles the output of extracted tables for the third page on declaration document which contain tw tables:

In [34]:
# Example usage
pdf_file = 'declaration.pdf'
pdf = open_pdf(pdf_file)

if pdf:
    page_num = 10  # Example page number
    tables = extract_tables_from_page(pdf, page_num)
    
    if tables:
        dataframes = process_tables(tables)
        if dataframes:  # Ensure there are DataFrames to display
            for i, df in enumerate(dataframes):
                print(f"Table {i + 1}:")
                print(df)
        else:
            print("No DataFrames created from the extracted tables.")
    else:
        print("No tables found on the specified page.")

    # Close the PDF
    pdf.close()

Table 1:
                                   Group                Line Additions  \
0  Schedule3\nDepreciation\n(fixedassets                   .      0.00
1                                   None                   .      0.00
2                                   None                   .      0.00
3                                   None                   .      0.00
4                                   None                   .      0.00
5                                   None  Total Depreciation      0.00

                  Asset Group Beginning Year Accum\nDepreciation  \
0  Tangible Movable\nProperty                               0.00
1             Heavy Machinery                               0.00
2             Light Machinery                               0.00
3     Tangible Fixed Property                               0.00
4                   Buildings                               0.00
5                        0.00                               0.00

  Beginning Year\nAcquisition Cost Beginning Year Book\nValue
0                             0.00                       0.00
1                             0.00                       0.00
2                             0.00                       0.00
3                             0.00                       0.00
4                             0.00                       0.00
5                             0.00                       0.00
Table 2:
                                   Group Line Depreciation  \
0  Schedule3\nDepreciation\n(fixedassets    .         0.00
1                                   None    .         0.00
2                                   None    .         0.00

  Depreciation Method Disposals Ending Year Accum\nDepreciation  \
0                0.00      0.00                            0.00
1                Pool      0.00                            0.00
2                Pool      0.00                            0.00

  Ending Year\nAcquisition Cost
0                          0.00
1                          0.00
2                          0.00

In [35]:
#example 
dataframes[0].describe() #table 1 EDA

,Group,Line,Additions,Asset Group,Beginning Year Accum\nDepreciation,Beginning Year\nAcquisition Cost,Beginning Year Book\nValue
count,1,6,6,6,6,6,6
unique,1,2,1,6,1,1,1
top,Schedule3\nDepreciation\n(fixedassets,.,0.00,Tangible Movable\nProperty,0.00,0.00,0.00
freq,1,5,6,1,6,6,6

In [ ]:
dataframes[1].describe() #table 2 EDA


### Summary
This Markdown explanation provides clarity on how the output is handled in your notebook, ensuring users understand how to access the extracted DataFrames based on the number of tables present in the PDF document.

<div style="background-color: #f9f9f9; padding: 20px; border-radius: 10px;">

## Future Learning Objectives

To enhance your skills and the functionality of this notebook, consider exploring the following areas:

- **Organizing DataFrames**: Learn techniques for sorting, filtering, and restructuring DataFrames to facilitate analysis and presentation.
  
- **Classifying Features by Impact and Importance**: Develop methods to evaluate and prioritize features based on their significance and effect on the outcomes.

- **Eliminating Special Characters**: Implement strategies to clean text data by removing special characters, ensuring uniformity and usability in further analysis.

- **Ensuring Data Consistency**: Test the extraction process on a variety of documents to identify and address inconsistencies, ensuring robust performance across different formats.

- **Generalizing the Code**: Refactor your code to create a more modular and reusable solution that can handle various declaration files with minimal modifications.

- **Natural Language Processing (NLP)**: Explore NLP techniques such as:
  - **Text Similarities**: Calculate similarities between text segments to find patterns or redundancies.
  - **Embeddings Computing**: Generate embeddings for textual data to capture semantic relationships.
  - **Named Entity Recognition (NER)**: Implement NER to identify and classify key information within the extracted data if needed.

### Questions & Feedback

If you encounter any challenges or have questions while working through this notebook or implementing these features, please feel free to ask for assistance. Collaboration and sharing insights can lead to better solutions!

</div>